export const ErrorCodes = {
  // General
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Practice Module
  AUDIO_FILE_MISSING: 'AUDIO_FILE_MISSING',
  AUDIO_FILE_TOO_LARGE: 'AUDIO_FILE_TOO_LARGE',
  INVALID_AUDIO_FORMAT: 'INVALID_AUDIO_FORMAT',
  TRANSCRIPTION_FAILED: 'TRANSCRIPTION_FAILED',
  ANALYSIS_FAILED: 'ANALYSIS_FAILED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_ALREADY_ENDED: 'SESSION_ALREADY_ENDED',

  // Review Module
  NO_REVIEW_AVAILABLE: 'NO_REVIEW_AVAILABLE',
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  EXERCISE_NOT_FOUND: 'EXERCISE_NOT_FOUND',
  ALREADY_SUBMITTED: 'ALREADY_SUBMITTED',
  REVIEW_ALREADY_COMPLETED: 'REVIEW_ALREADY_COMPLETED',

  // Analytics Module
  INSUFFICIENT_DATA: 'INSUFFICIENT_DATA',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',

  // External Services
  OPENAI_API_ERROR: 'OPENAI_API_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  REDIS_ERROR: 'REDIS_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
